$schema: "http://json-schema.org/schema#"

definitions:
  chapter:
    type: object
    properties:
      title: {type: string}
      description:
        oneOf: [{type: string}, {type: array}]
      text: {type: string}
    additionalProperties: false
    required: [title, description]
  chapters:
    type: array
    items: {$ref: "#/definitions/chapter"}
    additionalItems: false
  section:
    type: object
    properties:
      title: {type: string}
      description: {type: string}
      text: {type: string}
      chapters: {$ref: "#/definitions/chapters"}
    additionalProperties: false
    required: [title, description]
  sections:
    type: array
    items: {$ref: "#/definitions/section"}
    additionalItems: false
  document:
    type: object
    properties:
      title: {type: string}
      description: {type: string}
      sections: {$ref: "#/definitions/sections"}
    additionalProperties: false
    required: [title, description]
  documents:
    type: array
    items: {$ref: "#/definitions/document"}
    additionalItems: false
type: object
properties:
  documents: {$ref: "#/definitions/documents"}
additionalProperties: false
